{{- $configMap := toYaml .Values.exporterConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-tag-exporter.fullname" . }}-config
data:
  config.yaml: |
    config:
{{ tpl $configMap . | indent 6 }}
