{{- if .Values.secrets.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  {{- with .Values.secrets.sealedSecret.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "git-tag-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    GITLAB_API_TOKEN: {{ .Values.secrets.data.GITLAB_API_TOKEN }}
  template:
    data: null
    metadata:
      {{- with .Values.secrets.sealedSecret.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      name: {{ template "git-tag-exporter.fullname" . }}
      namespace: {{ .Values.namespace }}
    type: Opaque
{{- end }}