{{- if .Values.secrets.defaultSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "git-tag-exporter.fullname" . }}
  labels:
{{- include "git-tag-exporter.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}